### ISSUE TITLE
Outdated Readme

### ISSUE THREAD

**Issue by gSayak** [rumbleFTW/retinal-segmentation#1]
On going through the project I realized that the readme is outdated,
On cloning the repo on ones' local machine the next step is to go to 
```bash
cd retinal-segmentation 
```
There isn't an issue here but then the next step follows to go to a directory called **poetry-project**, on looking deeper I could not come across a poetry-project directory either on the root or inside any other folder

Would like that to get resolved!!

**Comment by rumbleFTW** [comment]
Thanks @gSayak for pointing-out the inconsistency in the README. 32a98bb fixes this issue. Cheers :clinking_glasses:.

**Comment by gSayak** [comment]
Hey we got to open this issue as 
```bash
poetry install 
```
This does not install the poetry , to install the poetry one has to run 
```bash
pip install poetry
```

**Comment by rumbleFTW** [comment]
We are assuming you already have poetry installed. Poetry can be installed by following [this](https://python-poetry.org/docs/). `poetry install` installs all of the dependencies in the current project.

**Comment by gSayak** [comment]
So now its **we** from **you** . I like where this is going ૮( ⸝⸝´꒳`⸝⸝)ა

**Comment by rumbleFTW** [comment]
🥺👉👈 Always has been.
